spring:
  application:
    name: spring-logging

  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:task
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG # SQL 쿼리문 로그 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩 파라미터 로그 출력

--- # local

spring:
  config:
    activate:
      on-profile: local

--- # test

spring:
  config:
    activate:
      on-profile: test

--- # dev

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: INFO # SQL 쿼리문 로그 출력 안 함
    org.hibernate.type.descriptor.sql.BasicBinder: OFF # 바인딩 파라미터 로그 출력 안 함