
### 할 일 등록
POST {{domain}}/api/v1/tasks
Content-Type: application/json

{
  "title": "할 일 등록 기능 개발",
  "description": "로깅 환경 구축 전, CRUD 기능 구현"
}

### 할 일 1건 조회
GET {{domain}}/api/v1/tasks/1
Content-Type: application/json

### 할 일 수정
PUT {{domain}}/api/v1/tasks/1
Content-Type: application/json

{
  "id": 1,
  "title": "할 일 등록 기능 개발",
  "description": "로깅 환경 구축 전, CRUD 기능 구현 - 수정 기능도 구현"
}

### 할 일 수정2
PUT {{domain}}/api/v1/tasks/1
Content-Type: application/json

{
  "id": 1,
  "completed": true
}